/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: malkaviana (https://sketchfab.com/malkaviana)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lecture-hall-316eaa267cef41878144dc7cf5317418
title: Lecture hall
*/

import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import HeroPage from './HeroPage'

export default function ClassModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('classroom.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-40, 40.83, -23.17]} rotation={[0, -Math.PI / 2, 0]}>
            <group position={[100.38, 58.44, 0]}>
              <mesh geometry={nodes.walls_strucco_0.geometry} material={materials.strucco}></mesh>
              <mesh geometry={nodes.walls_wood_0.geometry} material={materials.wood} />
              <mesh geometry={nodes.walls_black_0.geometry} material={materials.black} />
              <mesh geometry={nodes.walls_floor_0.geometry} material={materials.floor} />
              <mesh geometry={nodes.walls_tables_0.geometry} material={materials.tables} />
              <mesh geometry={nodes.walls_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.walls_dark_wood_0.geometry} material={materials.dark_wood} />
              <mesh geometry={nodes.walls_dark_wood_0_1.geometry} material={materials.dark_wood} />
              <mesh geometry={nodes.walls_dark_wood_0_2.geometry} material={materials.dark_wood} />
              <mesh geometry={nodes.walls_water_0.geometry} material={materials.water} />
              <mesh geometry={nodes.walls_ceramic_0.geometry} material={materials.ceramic} />
              <mesh geometry={nodes.walls_metal_0.geometry} material={materials.metal} />
              <mesh geometry={nodes.walls_papers_0.geometry} material={materials.papers} />
              <mesh geometry={nodes.walls_yellow_0.geometry} material={materials.yellow} />
              <mesh
                geometry={nodes.walls_screen_0.geometry}
                material={materials.screen}
              >
                <Html
                  wrapperClass="content-classroom"
                  // rotation-y={89.6}
                  // rotation-x={144.34}
                  // position={[-262.5, -31, 4]}
                  rotation-y={89.6}
                  rotation-x={0}
                  position={[-270, -120, -0.45]}
                  transform
                  occlude
                  scale={5.3}>
                  <div className="wrapper-classroom">
                    <HeroPage />
                  </div>
                </Html>
              </mesh>
              <mesh geometry={nodes['walls_Material_#538_0'].geometry} material={materials.Material_538} />
              <mesh geometry={nodes['walls_Material_#537_0'].geometry} material={materials.Material_537} />
              <mesh geometry={nodes['walls_Material_#539_0'].geometry} material={materials.Material_539} />
              <mesh geometry={nodes['walls_Material_#536_0'].geometry} material={materials.Material_536} />
              <mesh geometry={nodes['walls_Material_#540_0'].geometry} material={materials.Material_540} />
              <mesh geometry={nodes.walls_floor_0_1.geometry} material={materials.floor_0} />
              <mesh geometry={nodes.walls_strucco_dark_0.geometry} material={materials.strucco_dark} />
              <mesh geometry={nodes['walls_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('classroom.gltf')
