import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TheatreModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('theatre-model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={1} rotation={[0, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[10, -110.83, -23.17]} rotation={[0, -Math.PI / 2, 0]}>
            <group position={[100.38, 58.44, 0]}>
              <mesh geometry={nodes.seat_bases_1.geometry} material={materials.floor_red_fabric} />
              <mesh geometry={nodes.seat_bases_1_1.geometry} material={materials.floor_fabric} />
              <mesh geometry={nodes.screen.geometry} material={materials.screen} />
              <mesh geometry={nodes.ceiling01_1.geometry} material={materials.Wood} />
              <mesh geometry={nodes.ceiling01_1_1.geometry} material={materials.dark_black} />
              <mesh geometry={nodes.ceiling_top01.geometry} material={materials.stage_wood} />
              <mesh geometry={nodes.ceiling_top02.geometry} material={materials.Wood} />
              <mesh geometry={nodes.stage_top.geometry} material={materials.Wood} />
              <mesh geometry={nodes.saloon_back_1.geometry} material={materials.wall_back_fabric} />
              <mesh geometry={nodes.saloon_back_1_1.geometry} material={materials.wall_back_red} />
              <mesh geometry={nodes.saloon_back_1_2.geometry} material={materials.wall_back_black} />
              <mesh geometry={nodes.saloon_back_1_3.geometry} material={materials.Glass} />
              <mesh geometry={nodes.screen_back2.geometry} material={materials.floor_fabric} />
              <mesh geometry={nodes.projection_vindow.geometry} material={materials.Wood} />
              <mesh geometry={nodes.stage_1.geometry} material={materials.Wood} />
              <mesh geometry={nodes.stage_1_1.geometry} material={materials.stage_wood} />
              <mesh geometry={nodes.stage_1_2.geometry} material={materials.floor_fabric} />
              <mesh geometry={nodes.panels_left.geometry} material={materials.floor_fabric} />
              <mesh geometry={nodes.curtain_left.geometry} material={materials.curtains} />
              <mesh geometry={nodes.curtain_right.geometry} material={materials.curtains} />
              <mesh geometry={nodes.stairs_1.geometry} material={materials.black} />
              <mesh geometry={nodes.stairs_1_1.geometry} material={materials.floor_red_fabric} />
              <mesh geometry={nodes.corridor_base_1.geometry} material={materials.black} />
              <mesh geometry={nodes.corridor_base_1_1.geometry} material={materials.stairs_mix} />
              <mesh geometry={nodes.corridor_base_1_2.geometry} material={materials.stage_wood} />
              <mesh geometry={nodes.corridor_base_1_3.geometry} material={materials.corridor} />
              <mesh geometry={nodes.spots_ceiling2.geometry} material={materials.spots} />
              <mesh geometry={nodes.panels_right.geometry} material={materials.floor_fabric} />
              <mesh geometry={nodes.stage_sides.geometry} material={materials.Wood} />
              <mesh geometry={nodes.screen_back.geometry} material={materials.sign_boxes} />
              <mesh geometry={nodes.spots_ceiling1.geometry} material={materials.spots2} />
              <mesh geometry={nodes.exit_sign_01_1.geometry} material={materials['sign_boxes-2']} />
              <mesh geometry={nodes.exit_sign_01_1_1.geometry} material={materials._1___Default} />
              <mesh geometry={nodes.exit_sign_02_1.geometry} material={materials['sign_boxes-2']} />
              <mesh geometry={nodes.exit_sign_02_1_1.geometry} material={materials._1___Default} />
              <mesh geometry={nodes.exit_sign_03_1.geometry} material={materials['sign_boxes-2']} />
              <mesh geometry={nodes.exit_sign_03_1_1.geometry} material={materials._1___Default} />
              <mesh geometry={nodes.exit_sign_04_1.geometry} material={materials['sign_boxes-2']} />
              <mesh geometry={nodes.exit_sign_04_1_1.geometry} material={materials._1___Default} />
              <mesh geometry={nodes.exit_sign_05_1.geometry} material={materials['sign_boxes-2']} />
              <mesh geometry={nodes.exit_sign_05_1_1.geometry} material={materials._1___Default} />
              <mesh geometry={nodes.exit_sign_06_1.geometry} material={materials['sign_boxes-2']} />
              <mesh geometry={nodes.exit_sign_06_1_1.geometry} material={materials._1___Default} />
              <mesh geometry={nodes.speakers_L.geometry} material={materials.speakers} />
              <mesh geometry={nodes.speakers_B.geometry} material={materials.speakers} />
              <mesh geometry={nodes.speakers_R.geometry} material={materials.speakers} />
              <mesh geometry={nodes.speakers_F.geometry} material={materials.speakers} />
              <mesh geometry={nodes.speakers_panel.geometry} material={materials['speakers-2']} />
              <mesh geometry={nodes.spots_stagetop.geometry} material={materials.spots2} />
              <mesh geometry={nodes.salon_sides.geometry} material={materials.Wood} />
              <mesh geometry={nodes.salon_sides_top.geometry} material={materials.Wood} />
              <mesh geometry={nodes.main_walls.geometry} material={materials.blacks} />
              <mesh geometry={nodes.main_floor.geometry} material={materials.blacks} />
              <mesh geometry={nodes.main_ceiling.geometry} material={materials.blacks} />
              <mesh geometry={nodes.door_glassA1.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.doorA1.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_caseA.geometry} material={materials.Wood} />
              <mesh geometry={nodes.doorA2.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_glassA2.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.doorB1.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_glassB1.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.door_caseB.geometry} material={materials.Wood} />
              <mesh geometry={nodes.doorB2.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_glassB2.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.doorC.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_glassC.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.door_caseC.geometry} material={materials.Wood} />
              <mesh geometry={nodes.doorD.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_glassD.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.door_caseD.geometry} material={materials.Wood} />
              <mesh geometry={nodes.doorE.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_caseE.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_glassE.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.doorF.geometry} material={materials.Wood} />
              <mesh geometry={nodes.door_glassF.geometry} material={materials.Glass0} />
              <mesh geometry={nodes.door_caseF.geometry} material={materials.Wood} />
              <mesh geometry={nodes.seat_A01_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A01_1_1.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A01_1_2.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A02_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A02_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A02_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A03_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A03_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A03_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A04_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A04_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A04_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A05_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A05_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A05_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A06_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A06_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A06_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A12_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A12_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A12_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A11_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A11_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A11_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A10_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A10_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A10_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A09_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A09_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A09_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A08_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A08_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A08_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_A07_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_A07_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_A07_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B01_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B01_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B01_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B02_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B02_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B02_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B03_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B03_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B03_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B04_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B04_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B04_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B05_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B05_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B05_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B06_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B06_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B06_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B08_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B08_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B08_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B12_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B12_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B12_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B11_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B11_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B11_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B09_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B09_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B09_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B07_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B07_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B07_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_B10_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_B10_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_B10_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C01_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C01_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C01_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C02_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C02_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C02_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C03_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C03_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C03_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C04_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C04_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C04_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C05_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C05_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C05_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C06_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C06_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C06_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C07_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C07_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C07_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C08_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C08_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C08_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C09_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C09_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C09_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C10_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C10_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C10_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C11_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C11_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C11_1_2.geometry} material={materials.sit_plasts} />
              <mesh geometry={nodes.seat_C12_1.geometry} material={materials.sit_red} />
              <mesh geometry={nodes.seat_C12_1_1.geometry} material={materials.sit_metal_dark} />
              <mesh geometry={nodes.seat_C12_1_2.geometry} material={materials.sit_plasts} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('theatre-model.gltf')
